apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
	buildToolsVersion "34.0.0"
	compileSdkVersion 34

	namespace "io.github.zeroaicy.util"

	defaultConfig {
		minSdkVersion 26
		targetSdkVersion 34
		versionCode 1
		versionName "1.0"
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt')
		}
	}
}

publishing {
	publications {
		release(MavenPublication) {
			// JitPack 会自动覆盖 groupId 为 com.github.你的GitHub用户名 和 version 为 tag
			groupId = 'com.github.Agoni-agn'
			artifactId = 'agoni-java'
			version = '1.0'

			afterEvaluate {
				from components.release
			}
		}
	}
}
